"""empty message

Revision ID: 1dce8d845182
Revises: f4facdc48ee0
Create Date: 2017-04-04 14:45:09.985361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dce8d845182'
down_revision = 'f4facdc48ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('followable_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('followable_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followable')
    # ### end Alembic commands ###
