"""empty message

Revision ID: 478831377966
Revises: 266863f19175
Create Date: 2017-03-21 10:56:33.254783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478831377966'
down_revision = '266863f19175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taggable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('taggable_id', sa.Integer(), nullable=True),
    sa.Column('taggable_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taggable')
    op.drop_table('tags')
    # ### end Alembic commands ###
