"""empty message

Revision ID: 897a29d12da4
Revises: 2d8226198fbe
Create Date: 2017-03-15 11:03:11.687997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897a29d12da4'
down_revision = '2d8226198fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_companies')
    op.add_column('entries', sa.Column('content', sa.String(), nullable=False))
    op.drop_column('entries', 'description')
    op.drop_column('entries', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('entries', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('entries', 'content')
    op.create_table('entry_companies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entry_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], name='entry_companies_entry_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='entry_companies_pkey')
    )
    # ### end Alembic commands ###
