"""empty message

Revision ID: a2d1165d52e6
Revises: b7e5271871cd
Create Date: 2017-03-24 16:17:39.078623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2d1165d52e6'
down_revision = 'b7e5271871cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_search_vector', table_name='companies')
    op.drop_column('companies', 'search_vector')
    op.drop_index('ix_entries_search_vector', table_name='entries')
    op.drop_column('entries', 'search_vector')
    op.drop_index('ix_persons_search_vector', table_name='persons')
    op.drop_column('persons', 'search_vector')
    op.drop_index('ix_tags_search_vector', table_name='tags')
    op.drop_column('tags', 'search_vector')
    op.drop_index('ix_users_search_vector', table_name='users')
    op.drop_column('users', 'search_vector')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_search_vector', 'users', ['search_vector'], unique=False)
    op.add_column('tags', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('ix_tags_search_vector', 'tags', ['search_vector'], unique=False)
    op.add_column('persons', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('ix_persons_search_vector', 'persons', ['search_vector'], unique=False)
    op.add_column('entries', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('ix_entries_search_vector', 'entries', ['search_vector'], unique=False)
    op.add_column('companies', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('ix_companies_search_vector', 'companies', ['search_vector'], unique=False)
    # ### end Alembic commands ###
